# Generated by Django 4.2.11 on 2024-05-06 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacao',
            name='estoque',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='variacao',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='variacao',
            name='preco',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='variacao',
            name='preco_promocional',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='variacao',
            name='produto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='EcommerceApp.produto'),
            preserve_default=False,
        ),
    ]
