# Generated by Django 4.2.11 on 2024-05-06 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0002_variacao_estoque_variacao_nome_variacao_preco_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name_plural': 'Variações'},
        ),
    ]
